apiVersion: v1
kind: Service
metadata:
  name: demo-scg-green-svc
  namespace: gateway
  labels:
    app: demo-scg
spec:
  ports:
    - name: green
      port: 9090
      targetPort: http
  selector:
    app: demo-scg