apiVersion: v1
kind: Service
metadata:
  name: demo-scg-blue-svc
  namespace: gateway
  labels:
    app: demo-scg
spec:
  selector:
    app: demo-scg
  ports:
  - protocol: TCP
    name: http-blue
    port: 8080
    targetPort: http
