apiVersion: v1
kind: Service
metadata:
  name: demo-scg-green-svc
  namespace: gateway
  labels:
    app: demo-scg
spec:
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: http
  selector:
    app: demo-scg