apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway


configMapGenerator:
- files:
  - application.yaml
  name: demo-scg-configmap
generatorOptions:
  disableNameSuffixHash: true

resources:
- demo-scg-rollout.yaml
- demo-scg-blue-svc.yaml
- demo-scg-green-svc.yaml
- demo-scg-ingress.yaml


images:
- name: jei0486/demo-scg
  newTag: P18
