apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-fe-configmap
  namespace: fe
data:
  application.yaml: |
    spring:
      application:
        name: demo-fe
      messages:
        encoding: UTF-8
      thymeleaf:
        encoding: UTF-8

    springdoc:
      api-docs:
        path: /api-docs

    logging:
      level:
        org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

    custom.api.url.demo-api: http://demo-api-svc.api:8088

    management:
      endpoints:
        web:
          exposure:
            include: metrics, prometheus
    server:
      port: 9099
