apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fe

configMapGenerator:
- name: demo-fe-configmap
  files:
  - application.yaml
generatorOptions:
  disableNameSuffixHash: true

resources:
  - demo-fe.yaml
  - demo-fe-ingress.yaml

images:
  - name: jei0486/demo-fe
    newTag: v2