apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fe

configMapGenerator:
- files:
  - application.yaml
  name: demo-fe-configmap
generatorOptions:
  disableNameSuffixHash: true

resources:
- demo-fe.yaml

images:
- name: jei0486/demo-fe
  newTag: v0.0.6
