apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-api-configmap
  namespace: api
data:
  application.yaml: |
    spring:
      datasource:
        url: jdbc:mariadb://host.docker.internal:3306/demo_board?characterEncoding=UTF-8
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: osckorea!
      jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        properties:
          hibernate:
            format_sql: true
        hibernate:
          ddl-auto: none
      application:
        name: demo-api

    logging:
      level:
        org:
          springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
          hibernate:
            type:
              descriptor:
                sql: trace
      pattern:
        console: "%d{HH:mm:ss.SSS} [%-5level] [%t] %logger{36} - %msg%n"

    management:
      endpoints:
        web:
          exposure:
            include: metrics,prometheus
    server:
      port: 8088
