apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api

configMapGenerator:
- files:
  - application.yaml
  name: demo-api-configmap
generatorOptions:
  disableNameSuffixHash: true

resources:
- demo-api.yaml

images:
- name: docker.io/jei0486/demo-api
  newTag: v2
- name: jei0486/demo-api
  newTag: v0.0.8
