apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api

configMapGenerator:
- name: demo-api-configmap
  files:
  - application.yaml
generatorOptions:
  disableNameSuffixHash: true

resources:
- demo-api.yaml

images:
- name: jei0486/demo-api
  newTag: v2
