---
apiVersion: v1
kind: Service
metadata:
  name: demo-scg-svc
  namespace: gateway
  labels:
    app: demo-scg
spec:
  ports:
    - name: rest
      port: 9090
      targetPort: http
  selector:
    app: demo-scg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-scg
  namespace: gateway
  labels:
    app: demo-scg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-scg
  template:
    metadata:
      labels:
        app: demo-scg
    spec:
      containers:
        - name: demo-scg
          image: jei0486/demo-scg
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9090
          env:
            - name: 'spring.application.name'
              value: 'demo-scg'
            - name: 'spring.profiles.active'
              value: 'dev'
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
