server:
  port: 9090

resilience4j.circuitbreaker:
  configs:
    default:
        slidingWindowType: COUNT_BASED           # default: COUNT_BASED
        slidingWindowSize: 10                    # {통계건수}  default: 100
        minimumNumberOfCalls: 2                  # {최소요청횟수 default: 100 }
        failureRateThreshold: 50                 # {실패율 default: 50 }
        waitDurationInOpenState: 3000           # {Circuit Breaker유지시간 default: 60000 }
    instances:
      mycb:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger{36}.%method:%line] - %msg%n"

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://host.docker.internal:8080/auth/realms/demo/protocol/openid-connect/token
            authorization-uri: http://host.docker.internal:8080/auth/realms/demo/protocol/openid-connect/auth
            userinfo-uri: http://host.docker.internal:8080/auth/realms/demo/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          demo-client:
            provider: keycloak
            client-id: demo-client
            client-secret: 83f3e948-3f8c-49da-af7f-87a42d5ea6fd
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: demo-fe-board
          uri: http://demo-fe-svc.fe:9099/
          predicates:
            - name: Path
              args:
                patterns: /boards/**
            - name: Method
              args:
                methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
          metadata:
            connect-timeout: 2500
            response-timeout: 2500

        - id: demo-fe-api
          uri: http://demo-fe-svc.fe:9099/
          predicates:
            - Path=/api/**

        - id: demo-fe-circuit
          uri: http://demo-fe-svc.fe:9099/
          predicates:
            - Path=/boards/fail
          filters:
            - name: CircuitBreaker
              args:
                name: mycb
                fallbackUri: forward:/fallback    # fallback은 Circuit 상태와 상관 없이, fail조건에 해당된 경우 호출됨
