apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway


configMapGenerator:
- files:
  - application.yaml
  name: demo-scg-configmap
generatorOptions:
  disableNameSuffixHash: true

resources:
- demo-scg.yaml
- demo-scg-ingress.yaml

images:
- name: docker.io/jei0486/demo-scg
  newTag: v0.0.1
- name: jei0486/demo-scg
  newTag: v0.0.1
